apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: my-app-deployment
  namespace: XX_NAMESPACE_XX
spec:
  selector:
    matchLabels:
      app: my-app
  replicas: 2 
  template: # create pods using pod definition in this template
    metadata:
      namespace: XX_NAMESPACE_XX
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: group1registry.azurecr.io/services/my-hallo-app:XX_IMAGETAG_XX
        
        ports:
        - containerPort: 8080
        
      imagePullSecrets:
        - name:  acr-secret
